### ISSUE TITLE
ISO 3166-2 support

### ISSUE THREAD

**Issue by victoredwardocallaghan** [datasets/country-list#3]
Hi,

Thanks for this!

Would it be possible for you to add support for ISO 3166-2 so that Subdivision can be dealt with?
See https://en.wikipedia.org/wiki/ISO_3166-2
For example: https://en.wikipedia.org/wiki/ISO_3166-2:AU
[sic.] AU-NT

Thanks,
Edward.

**Comment by rgrp** [comment]
@victoredwardocallaghan hey this is a great suggestion. My one thought is that this `country-list` dataset is supposed to be very simple and clean and to serve those who *just* want the basic codes.

Can I suggest therefore opening an issue in the main Core Datasets registry at https://github.com/datasets/registry/issues - also if you are up for helping create this Data Package let us know!
